#!/bin/bash

./link_opengl
[ $(uname) = Darwin ] && {
  pkg-config --libs --cflags glfw3
} || {
  [ $(lsb_release -si) = Fedora ] && pkg-config --libs --cflags libglfw
  [ $(lsb_release -si) = Ubuntu ] && pkg-config --libs --cflags glfw3
}
